#!/bin/sh
VERSION=0.2.1
DISTRO=`lsb_release -sc`
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
set -e

# create debian source package
python setup.py sdist
rm -rf ~/build-guizero
mkdir ~/build-guizero
cp dist/guizero-$VERSION.tar.gz ~/build-guizero/guizero_$VERSION~$DISTRO.orig.tar.gz
cd ~/build-guizero
tar xvf guizero_$VERSION~$DISTRO.orig.tar.gz
cp -a $SCRIPTPATH/debian_$DISTRO ~/build-guizero/guizero-$VERSION/debian

# build .deb file
cd ~/build-guizero/guizero-$VERSION
debuild -us -uc

# copy debian source package and binary package to the dist/ directory
cp ~/build-guizero/python*deb $SCRIPTPATH/dist
cp ~/build-guizero/guizero_$VERSION~$DISTRO.orig.tar.gz $SCRIPTPATH/dist
cp ~/build-guizero/guizero_$VERSION~$DISTRO*.dsc $SCRIPTPATH/dist
cp ~/build-guizero/guizero_$VERSION~$DISTRO*.debian.tar.* $SCRIPTPATH/dist
rm -rf ~/build-guizero
