site_name: gui zero
pages:
  - About: about.md
  - Installation: index.md
  - How to...: howto.md
  - Getting Started: start.md
  - Alerts: alerts.md
  - App: app.md
  - Box: box.md
  - ButtonGroup: buttongroup.md
  - CheckBox: checkbox.md
  - Combo: combo.md
  - MenuBar: menubar.md
  - Picture: picture.md
  - PushButton: pushbutton.md
  - Slider: slider.md
  - Text: text.md
  - TextBox: textbox.md
  - Waffle: waffle.md
theme: readthedocs
